Repository department-of-veterans-affairs/vagov-content, pull requests merged in 2019-08, with the labels that each got.

#520 Change h4 to h3 to fix anomaly in FAQ section.
  pages/disability/eligibility.md
Labels: CMS content model anomaly

#522 Content-removing-VET-TEC-provider-chart
  pages/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program.md
Labels: Education

#496 Content wip shortening disability titles
  pages/disability/eligibility/hazardous-materials-exposure/agent-orange/testing-storage-areas.md
  pages/disability/eligibility/hazardous-materials-exposure/camp-lejeune-water-contamination.md
  pages/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-afghanistan.md
  pages/disability/eligibility/hazardous-materials-exposure/gulf-war-illness-southwest-asia.md
  pages/disability/eligibility/hazardous-materials-exposure/project-112-shad.md
  pages/disability/eligibility/illnesses-within-one-year-of-discharge.md
  pages/disability/eligibility/ptsd.md
  pages/disability/eligibility/special-claims/clothing-allowance.md
  pages/disability/eligibility/special-claims/temporary-increase-after-surgery-or-cast.md
  pages/disability/eligibility/special-claims/temporary-increase-for-time-in-hospital.md
  pages/disability/eligibility/special-claims/temporary-rating-prestabilization.md
  pages/disability/eligibility/special-claims/unemployability.md
Labels: Content Freeze Exception

#530 Content-vet-tec-anomaly-fix
  pages/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program.md
Labels: CMS content model anomaly
