Repository department-of-veterans-affairs/vagov-content, pull requests merged in 2019-11, with the labels that each got.

#576 SCO: Create Skeleton of SCO Resource Page in Github #19835
  assets/SCO_Handbook.pdf
  pages/education/school-resources.md
Labels: BAH, BAH-QA-Needed

#578 updated SCO intro section
  pages/education/school-resources.md
Labels: BAH

#580 SCO: Add 'Policies and procedures' content and styling to SCO Skeleton page #19891
  pages/education/school-resources.md
Labels: BAH

#579 Add training and guides to SCO skeleton page
  pages/education/school-resources.md
Labels: BAH, BAH-IR-Needed, BAH-QA-Needed

#577 SCO: Add right panel content to SCO Skeleton page #19908
  assets/img/hub-illustrations/education-sco.png
  pages/education/school-resources.md
Labels: BAH

#581 SCO Upcoming Events Section
  pages/education/school-resources.md
Labels: BAH

#584 19888: SCO: Add Announcements content and styling to SCO Skeleton page
  pages/education/school-resources.md
Labels: BAH

#586 School Resources - SCO Events and Announcements
  pages/education/school-resources.md
Labels: BAH

#591 SCO: Update UI based on UX team feedback #19965
  pages/education/school-resources.md
Labels: BAH, BAH-QA-Needed

#588 Bah 19964
  assets/SCO_Handbook.pdf
  pages/education/school-resources.md
Labels: BAH, BAH-IR-Needed, BAH-QA-Needed

#592 SCO: Update SCO Page URL #19967
  pages/school-administrators.md
Labels: BAH, BAH-QA-Needed

#593 19988: AC 2, 4, and 5 for 19988
  pages/school-administrators.md
Labels: BAH, BAH-IR-Needed, BAH-QA-Needed

#589 19968: SCO - Axe check failure: Heading levels should only increase by one
  pages/school-administrators.md
Labels: BAH, BAH-QA-Needed

#595 SCO: Update SCO Page BreadCrumble
  pages/school-administrators.md
Labels: BAH

#597 Add new va form 10-10068 pdfs
  assets/VA_Form_10-10068.pdf
  assets/VA_Form_10-10068b.pdf
Labels: enhancement

#598 ui/ux feedback for SCO page
  pages/school-administrators.md
Labels: BAH, BAH-QA-Needed

#596 Analytics Implementation for Resources for Schools [SCO Migration] #3055
  pages/school-administrators.md
Labels: BAH, BAH-QA-Needed

#599 Bah 19965 fixes
  pages/school-administrators.md
Labels: BAH, BAH-IR-Needed

#594 SCO: New SCO Migration Page is available in production #20000
  pages/school-administrators.md
Labels: BAH, BAH-QA-Needed

#601 SCO: Last Updated Date wrong#20016, Analytics Implementation for Resources for Schools [SCO Migration] #3055
  pages/school-administrators.md
Labels: BAH
