Repository department-of-veterans-affairs/vagov-content, pull requests merged in 2019-07, with the labels that each got.

#484 Updated post-9-11.md webpage
  pages/education/about-gi-bill-benefits/post-9-11.md
Labels: BAH

#485 update 107 question text to match bold and italic requirements
  pages/education/about-gi-bill-benefits/post-9-11.md
Labels: BAH

#459 Make anomaly edits and add headings in Education pages
  pages/education/about-gi-bill-benefits.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/co-op-training.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/correspondence-training.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/entrepreneurship-training.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/flight-training.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/non-college-degree-programs.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/on-the-job-training-apprenticeships.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/online-distance-learning.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/study-at-foreign-schools.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/test-fees.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/tuition-assistance-top-up.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/tutor-assistance.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/undergraduate-graduate-programs.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/vettec-high-tech-program.md
  pages/education/about-gi-bill-benefits/how-to-use-benefits/work-study.md
  pages/education/about-gi-bill-benefits/montgomery-active-duty.md
  pages/education/about-gi-bill-benefits/montgomery-active-duty/buy-up.md
  pages/education/about-gi-bill-benefits/montgomery-selected-reserve.md
  pages/education/about-gi-bill-benefits/post-9-11.md
  pages/education/about-gi-bill-benefits/post-9-11/yellow-ribbon-program.md
  pages/education/after-you-apply.md
  pages/education/apply-for-education-benefits/application/1990.md
  pages/education/apply-for-education-benefits/application/1990E.md
  pages/education/apply-for-education-benefits/application/1990N.md
  pages/education/apply-for-education-benefits/application/1995-STEM.md
  pages/education/apply-for-education-benefits/application/1995.md
  pages/education/apply-for-education-benefits/application/5490.md
  pages/education/apply-for-education-benefits/application/5495.md
  pages/education/apply-restore-benefits.md
  pages/education/benefit-rates.md
  pages/education/change-gi-bill-benefits.md
  pages/education/choosing-a-school.md
  pages/education/choosing-a-school/principles-of-excellence.md
  pages/education/compare-education-benefits.md
  pages/education/education-and-career-counseling.md
  pages/education/eligibility.md
  pages/education/gi-bill/post-9-11/ch-33-benefit.md
  pages/education/how-to-apply.md
  pages/education/index.md
  pages/education/opt-out-information-sharing.md
  pages/education/opt-out-information-sharing/opt-out-form-0993.md
  pages/education/other-va-education-benefits.md
  pages/education/other-va-education-benefits/national-call-to-service-program.md
  pages/education/other-va-education-benefits/reap.md
  pages/education/other-va-education-benefits/veap.md
  pages/education/submit-school-feedback.md
  pages/education/survivor-dependent-benefits.md
  pages/education/survivor-dependent-benefits/dependents-education-assistance.md
  pages/education/survivor-dependent-benefits/fry-scholarship.md
  pages/education/transfer-post-9-11-gi-bill-benefits.md
Labels: CMS content model anomaly

#490 Update PTSD anchor link.
  pages/disability/eligibility/ptsd.md
Labels: CMS content model anomaly, Content Freeze Exception

#514 Fix schema.org markup on 9/11 GI bill page.
  pages/education/about-gi-bill-benefits/post-9-11.md
Labels: CMS content model anomaly

#517 Move ids from <section> to <h2> to help with FAQs migrations.
  pages/disability/file-an-appeal/board-of-veterans-appeals.md
Labels: CMS content model anomaly

#516 Fix schema.org markup in Education - How to Apply
  pages/education/how-to-apply.md
Labels: CMS content model anomaly

#518 Add missing </div></div> to help migration script parse the page.
  pages/burials-memorials/veterans-burial-allowance.md
Labels: CMS content model anomaly

#515 Fix schema.org markup on flight training page
  pages/education/about-gi-bill-benefits/how-to-use-benefits/flight-training.md
Labels: CMS content model anomaly
